### ISSUE TITLE
애널리틱스 관련

### ISSUE THREAD

**Issue by mingyoq** [WisdomIT/chzzk-vote#8]
안녕하세요.
먼저 좋은 서비스 감사드립니다!

소스 코드를 살펴보니 프록시 서버를 사용하고(프록시 서버가 로깅을 하지 않더라도 전송받으므로), Google Analytics와 Discord 웹훅에 채널 정보를 보내는 것으로 보이는데,

초기 화면에 "데이터는 컴퓨터에 저장되며, 서버에는 전송되지 않습니다" 문구는 부적절하다고 보입니다.

또한 이에 따른 개인정보처리방침이 필요할 것으로 생각됩니다.

감사합니다.

**Comment by WisdomIT** [comment]
넵 의견 감사합니다!

데이터가 컴퓨터에 저장된다는 것은 설정 데이터를 의미하는 것이었는데, 충분히 오해의 소지가 있다고 저도 생각되네요.
구글 애널리틱스와 웹훅을 최근에 추가하면서 고려하지 못했던 것 같습니다.
조만간 해당 문구를 수정하고 관련 사항을 개선하도록 하겠습니다.
